// react-example/src/scenarios/2-complex-structure/TwoParent.js
import React, { useState } from 'react';

import { TwoChild } from './TwoChild';

const TwoParent = () => {
  const [resetForm, setResetForm] = useState({ reset: false });

  const handleResetFormClick = () => {
    setResetForm({ reset: true });
  };

  return (
    <>
      <TwoChild resetForm={resetForm} />
      <button onClick={handleResetFormClick}>reset form</button>
    </>
  );
};

export { TwoParent };

// angular/src/scenarios/2-primitive-on-parent-not-working/two-parent.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "two-parent",
  template: `
    <two-child [resetForm]="resetForm"></two-child>
    <button (click)="onResetForm()">reset form</button>
  `
})
export class TwoParentComponent {
  resetForm = false;

  onResetForm() {
    this.resetForm = true;
  }
}
